CREATE TABLE classes (
    Id INT PRIMARY KEY AUTO_INCREMENT
);

CREATE TABLE courses (
    Id INT PRIMARY KEY AUTO_INCREMENT
);

CREATE TABLE lecturers (
    Id INT PRIMARY KEY AUTO_INCREMENT
);

CREATE TABLE students_temp (
    Id INT PRIMARY KEY AUTO_INCREMENT
);

CREATE TABLE study_hours_extended (
    Id INT PRIMARY KEY AUTO_INCREMENT
);
